/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Multitel
 */
public class PanelVehiculo1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelVehiculo1
     */
    public PanelVehiculo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarVehiculo = new javax.swing.JButton();
        btnActualizarVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        txtProyecto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxDepartamento = new javax.swing.JComboBox<>();
        ComboBoxPais = new javax.swing.JComboBox<>();
        txtBuscarVehiculo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnLimpiarVehiculos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculo = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(2527, 1159));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehículo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesPaneles/Diseño sin título.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 290));

        btnAgregarVehiculo.setBackground(new java.awt.Color(53, 233, 250));
        btnAgregarVehiculo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnAgregarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVehiculo.setText("Agregar");
        btnAgregarVehiculo.setBorder(null);
        btnAgregarVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAgregarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 150, 50));

        btnActualizarVehiculo.setBackground(new java.awt.Color(53, 233, 250));
        btnActualizarVehiculo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnActualizarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarVehiculo.setText("Actualizar");
        btnActualizarVehiculo.setBorder(null);
        btnActualizarVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnActualizarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 150, 50));

        btnEliminarVehiculo.setBackground(new java.awt.Color(53, 233, 250));
        btnEliminarVehiculo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnEliminarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVehiculo.setText("Eliminar");
        btnEliminarVehiculo.setBorder(null);
        btnEliminarVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 150, 50));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        jPanel2.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, -1));

        txtProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProyectoActionPerformed(evt);
            }
        });
        jPanel2.add(txtProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 150, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel9.setText("Proyecto");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel10.setText("Departamento Área");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 220, -1));
        jPanel2.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 170, -1));
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 170, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel6.setText("Modelo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel7.setText("País");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel8.setText("Estado");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel4.setText("Matricula");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel2.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 230, -1));
        jPanel2.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel3.setText("Marca");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel5.setText("Tipo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        ComboBoxDepartamento.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ComboBoxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Claro proyectos", "Claro ampliacion", "Movistar", "Administracion", "Presidencia", "TH", "Claro Masivo", " " }));
        ComboBoxDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(ComboBoxDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 210, 40));

        ComboBoxPais.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EL Salvador", "Nicaragua" }));
        ComboBoxPais.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.add(ComboBoxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 170, -1));

        txtBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVehiculoActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuscarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 370, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setText("Buscar");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        btnLimpiarVehiculos.setBackground(new java.awt.Color(51, 51, 255));
        btnLimpiarVehiculos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnLimpiarVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarVehiculos.setText("Limpiar ");
        btnLimpiarVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnLimpiarVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 1000, 260));

        jPanel3.setBackground(new java.awt.Color(6, 131, 206));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 190));

        tablaVehiculo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tablaVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Marca", "Tipo", "Modelo", "País", "Estado", "Proyecto", "Departamento Área"
            }
        ));
        jScrollPane1.setViewportView(tablaVehiculo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 1040, 660));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Diseño sin título (3).png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -200, 2260, 1400));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 2530, 1160));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProyectoActionPerformed

    private void txtBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxDepartamento;
    public javax.swing.JComboBox<String> ComboBoxPais;
    public javax.swing.JButton btnActualizarVehiculo;
    public javax.swing.JButton btnAgregarVehiculo;
    public javax.swing.JButton btnEliminarVehiculo;
    public javax.swing.JButton btnLimpiarVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaVehiculo;
    public javax.swing.JTextField txtBuscarVehiculo;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtMarca;
    public javax.swing.JTextField txtMatricula;
    public javax.swing.JTextField txtModelo;
    public javax.swing.JTextField txtProyecto;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
